# Generated by Django 3.1 on 2020-08-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_bids_comments_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='category',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auction_list',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auction_list',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Other',
        ),
    ]
