# Generated by Django 3.1 on 2020-08-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200819_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='description',
            field=models.CharField(default='', max_length=64),
        ),
    ]
