# Generated by Django 3.1 on 2020-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200820_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
