# Generated by Django 3.1 on 2020-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200821_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
