# Generated by Django 3.1 on 2020-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_list_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bids',
        ),
        migrations.AddField(
            model_name='bids',
            name='list_bids',
            field=models.IntegerField(default=0),
        ),
    ]
