# Generated by Django 3.1 on 2020-08-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bids_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='list_bids',
            new_name='your_bids',
        ),
    ]
