# Generated by Django 3.1 on 2020-08-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_watchlist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closed_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_list', models.CharField(default='', max_length=64)),
                ('starting_bid', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=64)),
                ('category', models.CharField(default='', max_length=64)),
                ('list_name', models.CharField(default='', max_length=64)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.CharField(default='', max_length=64)),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
