# Generated by Django 3.1 on 2020-08-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200827_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closed_listing',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='closed_listing',
            name='winner',
            field=models.CharField(default='', max_length=64),
        ),
    ]
