# Generated by Django 3.1 on 2020-08-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200827_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
