# Generated by Django 3.1 on 2020-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20200827_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='closed_listing',
            name='bids',
            field=models.FloatField(default=0),
        ),
    ]
