# Generated by Django 3.1 on 2020-08-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20200828_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64)),
                ('category_auction_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_auction_list_id', to='auctions.auction_list')),
            ],
        ),
    ]
